### ISSUE TITLE
error : go get github.com/danhunsaker/calends' returned a non-zero code: 2 on docker build

### ISSUE THREAD

**Issue by unexpand** [danhunsaker/calends#6]
Not sure if something is broken in  github.com/knz/strtime 

```
Step 9/20 : RUN go get github.com/danhunsaker/calends
 ---> Running in 8bae3e0c6277
# github.com/knz/strtime
exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c go get github.com/danhunsaker/calends' returned a non-zero code: 2
```

**Comment by danhunsaker** [comment]
Looks like you need to install GCC. `github.com/knz/strtime` has some C code that it needs to compile in order to work properly.

I'm curious how you're using calends, though!

**Comment by unexpand** [comment]
Thanks, that works and Thanks for Calends too. 
It made it super easy for us to work with Unix time and Gregorian time.
